"use client";
import { useLocale, LocaleControls } from "./locale";
import Link from "next/link";
import { ArrowDown, ArrowUpRight, Database, FileCheck2, Workflow } from "lucide-react";
import { Brand } from "./brand";
import { PublicPlan } from "./subscription";
import { ProductGuide, ProductFaq } from "./product-guide";
export default function Home() {
    const { t } = useLocale();
    return <main className="public-site">
    <header className="public-header"><Link href="/" aria-label={t("DPsoft home")}><Brand /></Link><LocaleControls/><nav aria-label={t("Main navigation")}><a href="#platform">{t("Platform")}</a><a href="#approach">{t("Our approach")}</a><a href="#subscription">{t("Subscription")}</a></nav><Link className="public-login" href="/workspace">{t("Sign in ")}<ArrowUpRight size={15}/></Link></header>
    <section className="public-hero"><div className="hero-index"><span>{t("THE OPERATIONAL WORKSPACE")}</span><span>{t("01 \u2014 DP / SOFT")}</span></div><div className="public-hero-grid"><div><h1>{t("The answer is in")}<br />{t("your business.")}<br /><em>{t("Bring it into focus.")}</em></h1><p>{t("A considered workspace for connecting business data, asking better questions and keeping the evidence behind every answer.")}</p><div className="public-actions"><Link className="public-cta" href="/workspace">{t("Open your workspace ")}<ArrowUpRight size={18}/></Link><a className="editorial-link" href="#platform">{t("Explore the platform ")}<ArrowDown size={14}/></a></div><span className="public-caption">{t("Built around your systems. Starting with PostgreSQL.")}</span></div><div className="editorial-object" aria-label={t("Product principle: source, scope, evidence")}><div className="object-top">{t("DPSOFT FIELD NOTES ")}<span>{t("NO. 001")}</span></div><div className="object-monogram"><Brand compact/></div><div className="object-rule"/><p>{t("Clarity is not another dashboard.")}<br />{t("It is knowing where the answer came from.")}</p><ol><li><span>{t("01")}</span>{t(" A source you control")}</li><li><span>{t("02")}</span>{t(" A scope you define")}</li><li><span>{t("03")}</span>{t(" Evidence you retain")}</li></ol><div className="object-bottom">{t("SOURCE \u2192 SCOPE \u2192 EVIDENCE")}</div></div></div></section>
    <section className="public-principles"><span>{t("LESS GUESSWORK.")}<br />{t("MORE CONTEXT.")}</span><p>{t("Your database remains the source.")}</p><p>{t("Your team defines the access.")}</p><p>{t("Your answers retain their origin.")}</p></section>
    <section className="public-section" id="platform"><div className="section-intro"><span className="public-kicker">{t("01 / THE PLATFORM")}</span><h2>{t("Three layers.")}<br /><em>{t("One coherent workflow.")}</em></h2><p>{t("No disconnected collection of assistants. A path from an authorized source to a business answer your team can inspect.")}</p></div><div className="capability-grid"><article><Database size={24}/><span className="card-index">{t("01")}</span><h3>{t("Connect with intention.")}</h3><p>{t("Connect a PostgreSQL database, inspect its schema and explicitly select the source and columns available to the revenue tool.")}</p><ul><li>{t("Encrypted stored credentials")}</li><li>{t("Read-only query execution")}</li><li>{t("Connection testing")}</li></ul></article><article><Workflow size={24}/><span className="card-index">{t("02")}</span><h3>{t("Give the agent a boundary.")}</h3><p>{t("Create a purpose-specific agent linked to an authorized connector. Ask about monthly invoice revenue using your configured source.")}</p><ul><li>{t("Explicit tool assignments")}</li><li>{t("Source-to-agent map")}</li><li>{t("Persisted conversation history")}</li></ul></article><article><FileCheck2 size={24}/><span className="card-index">{t("03")}</span><h3>{t("Keep the reasoning grounded.")}</h3><p>{t("Inspect recorded source metadata, review workspace activity and export the evidence currently loaded in your workspace.")}</p><ul><li>{t("Searchable evidence library")}</li><li>{t("JSON evidence export")}</li><li>{t("Filterable audit events")}</li></ul></article></div></section>
    <section className="public-manifesto" id="approach"><span className="public-kicker">{t("02 / A DIFFERENT STARTING POINT")}</span><h2>{t("Not more noise.")}<br /><em>{t("More useful work.")}</em></h2><div><p>{t("Business software should respect the way your company works: its existing systems, its definitions and its responsibilities.")}</p><p>{t("DPsoft starts with a narrow, inspectable workflow. Connect a source. Authorize a calculation. Ask a question. Review what came back. Expand from there.")}</p><Link href="/workspace" className="editorial-link">{t("Start with your data ")}<ArrowUpRight size={16}/></Link></div></section>
    <section className="public-section public-pricing" id="subscription"><div className="section-intro"><span className="public-kicker">{t("03 / YOUR WORKSPACE")}</span><h2>{t("A clear place")}<br /><em>{t("to begin.")}</em></h2><p>{t("Create your account, configure your organization and manage subscriptions from the workspace. Payment availability and price are retrieved from the billing provider.")}</p></div><PublicPlan /></section>
    <ProductGuide />
    <ProductFaq />
    <footer className="public-footer"><Link href="/" aria-label={t("DPsoft home")}><Brand compact/></Link><span>{t("Business, connected.")}</span><Link href="/workspace">{t("Access your workspace ")}<ArrowUpRight size={14}/></Link></footer>
  </main>;
}
