export type GuideCopy = {
  title: string; intro: string; valueTitle: string; value: string;
  stepsTitle: string; steps: string[]; installTitle: string;
  web: string; mac: string; mobile: string; securityTitle: string; security: string;
  faqTitle: string; faq: [string, string][]; docs: string;
  planNote: string; plannedRuns: string; audiences: string[];
};
export const guideCopy: Record<"en" | "pt" | "fr" | "es" | "de", GuideCopy> = {
  en: {
    title: "Know what your business data is telling you.",
    intro: "DPsoft connects an authorized PostgreSQL source to a workspace for monthly invoice revenue, period comparisons and evidence review. It complements your existing software; it is not an accounting system or a universal computer operator.",
    valueTitle: "A practical reason to use it",
    value: "Use it when your team repeatedly checks revenue and needs to see the source behind a result. Instead of reconstructing the calculation each time, select a month, run the authorized report and inspect its source and record count. Any time saved depends on your data quality and workflow; financial review remains your responsibility.",
    stepsTitle: "From your source to a checked result",
    steps: ["Create an account and an organization. The owner manages billing and device pairing. Account creation alone does not activate paid tools.", "In Connectors, supply a dedicated PostgreSQL account with SELECT-only permissions. Ask your database administrator to approve network access and TLS. Do not expose your database to the whole internet.", "Inspect the schema and authorize the invoice table, amount column, date column and source currency. Only connect data you are permitted to use.", "Open Report tools, select the source and month, and optionally compare another month. Export CSV and review the UTC date boundaries. Agent chat additionally requires a configured AI provider and active access."],
    installTitle: "Browser first. Local access by explicit choice.",
    web: "Web: open dpsoft.space/workspace in a current browser. There is no desktop installation required for the web workspace. Tool access depends on configuration and subscription availability.",
    mac: "macOS technical preview: the connector is a Node.js 22+ command-line tool from the source repository, not a signed installer. It pairs with a one-time code and sends a manual heartbeat. Saving an approved text report is a separate local action; cloud jobs are not dispatched to it.",
    mobile: "Mobile: use the website in your browser. Native iOS/Android apps, offline mode and control of other mobile apps are not available.",
    securityTitle: "Defined controls, honest limits",
    security: "The implementation includes HTTPS, encrypted stored connector credentials, organization checks, read-only revenue queries and recorded audit events. Pairing codes expire after 10 minutes; device credentials expire after 30 days and can be revoked. This is not a guarantee of absolute security or a claim of certification. No independent security audit is claimed. Local preview credentials use a permission-restricted file, not macOS Keychain.",
    faqTitle: "Questions worth answering before you start",
    faq: [
      ["Which software can I connect?", "The implemented business-data connector is PostgreSQL. MCP can standardize a compatible integration, but it does not make every legacy, web or desktop application compatible. Other systems need a separately implemented and tested connector."],
      ["What does the revenue number mean?", "It sums the authorized amount column for the selected UTC month. It is not automatically profit, cash received or tax-adjusted revenue. The source currency is declared by the operator; confirm your accounting definitions before using the result."],
      ["Does DPsoft change my business records?", "The current revenue tool is read-only. Remote edits, unattended desktop control and automatic actions inside customer software are not enabled."],
      ["Can it send invoices or reports by email or WhatsApp?", "Not in the current release. CSV/JSON exports are available for manual review and sharing. Email delivery, WhatsApp delivery and fiscal invoice issuance are not included as working features."],
      ["What information reaches the AI provider?", "In agent chat, the question and authorized tool result are sent to the configured provider. Direct report generation does not require an AI call. Never include unnecessary personal or confidential information; review your organization's data policy first."],
      ["Can I install it on my Mac?", "A technical user can build the CLI from authorized source access using Node.js 22+. The guide below covers pairing and local report approval. A notarized app, automatic updates and remote task execution are still pending; there is no installer download to promise today."],
      ["How do I pay and what is included?", "Essential, Business and Scale are launch proposals. Purchases remain closed until merchant configuration and usage controls are ready. Proposed run allowances are not active entitlements. The hosted checkout, when enabled, must show the actual amount, currency and billing period before payment."],
      ["Why can the displayed currency differ from checkout?", "Local-currency values are indicative conversions, not guaranteed settlement rates. Check the provider's billing currency and any bank fees. Browser language and region suggest preferences; you can change them manually."],
      ["Does pairing give DPsoft access to my whole computer?", "No. The current device credential permits heartbeat only. Pairing does not grant screen, keyboard, file browsing or remote execution access. You can revoke a device in Connectors."],
      ["Can I cancel or export my work?", "When Stripe billing is configured, the owner can open its portal to manage the subscription according to the displayed terms. Reports export to CSV; the evidence library exports loaded records to JSON. These are not a complete account archive, and there is no self-service account-deletion flow yet."]
    ],
    docs: "Read the technical installation guide", planNote: "Launch proposal — not currently purchasable. Quotas must be enforced before sales open.", plannedRuns: "Proposed standard runs / month", audiences: ["For a focused revenue-review workflow.", "For a growing volume of recurring analysis.", "For higher-volume operations with defined budgets."]
  },
  pt: {
    title: "Perceba o que os dados da sua empresa dizem.",
    intro: "O DPsoft liga uma fonte PostgreSQL autorizada a um espaço de trabalho para consultar faturação mensal, comparar períodos e verificar a origem dos resultados. Complementa o software existente; não é um programa de contabilidade nem um operador universal de computadores.",
    valueTitle: "Uma razão prática para utilizar",
    value: "É útil quando a equipa consulta faturação repetidamente e precisa de confirmar de onde veio cada resultado. Em vez de reconstruir o cálculo, seleciona o mês, gera o relatório autorizado e verifica a fonte e o número de registos. A poupança de tempo depende da qualidade dos dados e do processo; a validação financeira continua a ser sua responsabilidade.",
    stepsTitle: "Da sua fonte a um resultado verificado",
    steps: ["Crie uma conta e uma organização. O proprietário gere a assinatura e o emparelhamento de dispositivos. Criar uma conta não ativa, por si só, ferramentas pagas.", "Em Connectors, introduza uma conta PostgreSQL dedicada, apenas com permissões SELECT. Peça ao administrador da base de dados para autorizar a rede e o TLS. Não exponha a base de dados a toda a internet.", "Inspecione o esquema e autorize a tabela de faturas, a coluna de valor, a coluna de data e a moeda da fonte. Ligue apenas dados que tem autorização para utilizar.", "Abra Report tools, selecione a fonte e o mês e, se necessário, compare outro período. Exporte CSV e confirme os limites de datas em UTC. O chat com agente exige também um fornecedor de IA configurado e acesso ativo."],
    installTitle: "Primeiro no navegador. Acesso local por escolha explícita.",
    web: "Web: abra dpsoft.space/workspace num navegador atualizado. Não precisa de instalar um programa para utilizar o workspace web. O acesso às ferramentas depende da configuração e da disponibilidade das assinaturas.",
    mac: "Prévia técnica macOS: o conector é uma ferramenta de linha de comandos que exige Node.js 22+ e acesso ao código, não um instalador assinado. Emparelha com um código de uso único e verifica a ligação manualmente. Guardar um relatório de texto aprovado é uma ação local separada; não recebe tarefas da nuvem.",
    mobile: "Mobile: utilize o website no navegador. Ainda não existem aplicações nativas iOS/Android, modo offline ou controlo de outras aplicações do telemóvel.",
    securityTitle: "Controlos definidos, limites transparentes",
    security: "A implementação inclui HTTPS, credenciais de conectores guardadas com encriptação, verificações por organização, consultas de faturação apenas de leitura e eventos de auditoria. Os códigos de emparelhamento expiram em 10 minutos; as credenciais dos dispositivos expiram em 30 dias e podem ser revogadas. Não é garantia de segurança absoluta nem certificação. Não alegamos uma auditoria de segurança independente. A prévia local guarda credenciais num ficheiro com permissões restritas, não no Porta-chaves do macOS.",
    faqTitle: "Perguntas importantes antes de começar",
    faq: [
      ["Que softwares posso conectar?", "O conector de dados empresariais implementado é PostgreSQL. O MCP pode padronizar uma integração compatível, mas não torna qualquer software antigo, web ou desktop automaticamente compatível. Cada sistema adicional precisa de um conector implementado e testado."],
      ["O que significa o valor de faturação?", "É a soma da coluna de valor autorizada no mês selecionado, em UTC. Não significa automaticamente lucro, dinheiro recebido ou faturação ajustada a impostos. A moeda é declarada pelo operador; confirme as definições contabilísticas da sua empresa."],
      ["O DPsoft altera os meus registos?", "A ferramenta de faturação atual é apenas de leitura. Edições remotas, controlo autónomo do computador e ações automáticas dentro de outros softwares não estão ativos."],
      ["Envia faturas ou relatórios por email e WhatsApp?", "Ainda não nesta versão. Pode exportar CSV/JSON para rever e partilhar manualmente. Envio de email, envio por WhatsApp e emissão fiscal de faturas não são apresentados como recursos funcionais."],
      ["Que dados são enviados ao fornecedor de IA?", "No chat com agente, a pergunta e o resultado da ferramenta autorizada são enviados ao fornecedor configurado. A geração direta de relatórios não exige uma chamada de IA. Evite dados pessoais ou confidenciais desnecessários e confirme a política da sua organização."],
      ["Como instalo no meu Mac?", "Um utilizador técnico pode compilar o CLI com Node.js 22+ e acesso autorizado ao repositório. O guia abaixo explica o emparelhamento e a aprovação de relatórios locais. A app autenticada pela Apple, as atualizações automáticas e as tarefas remotas ainda estão pendentes; não existe um instalador para descarregar nesta versão."],
      ["Como pago e o que está incluído?", "Essential, Business e Scale são propostas de lançamento. As compras continuam fechadas até a configuração comercial e os limites de utilização estarem prontos. As quotas propostas não são direitos de utilização ativos. Quando habilitado, o checkout deve mostrar o valor real, a moeda e o período antes do pagamento."],
      ["Porque pode a moeda apresentada diferir da cobrança?", "Os valores em moeda local são conversões indicativas, não taxas de liquidação garantidas. Confirme a moeda do checkout e as taxas do banco. O idioma e a região do navegador sugerem preferências; pode alterá-las manualmente."],
      ["Emparelhar dá acesso a todo o computador?", "Não. A credencial atual permite apenas verificar a ligação. Não concede acesso ao ecrã, teclado, navegação de ficheiros nem execução remota. Pode revogar o dispositivo em Connectors."],
      ["Posso cancelar ou exportar os meus dados?", "Quando o Stripe estiver configurado, o proprietário pode abrir o portal para gerir a assinatura segundo as condições apresentadas. Os relatórios exportam CSV e a biblioteca de evidências exporta os registos carregados em JSON. Isso não constitui um arquivo completo da conta; ainda não existe eliminação de conta por autosserviço."]
    ],
    docs: "Ler o guia técnico de instalação", planNote: "Proposta de lançamento — compras indisponíveis. Os limites precisam de ser aplicados antes da abertura das vendas.", plannedRuns: "Execuções standard propostas / mês", audiences: ["Para um processo focado de análise da faturação.", "Para um volume crescente de análises recorrentes.", "Para operações de maior volume com orçamento definido."]
  },
  es: {
    title: "Entienda lo que dicen los datos de su empresa.", intro: "DPsoft conecta una fuente PostgreSQL autorizada para consultar facturación mensual, comparar periodos y revisar evidencias. Complementa su software; no sustituye la contabilidad ni controla cualquier ordenador.",
    valueTitle: "Valor práctico", value: "Consulte una fuente autorizada sin reconstruir cada cálculo. Revise el origen, el mes y el número de registros. El ahorro depende de la calidad de los datos; la revisión financiera sigue siendo responsabilidad de su equipo.",
    stepsTitle: "Cómo empezar", steps: ["Cree una cuenta y una organización. El propietario gestiona pagos y dispositivos; registrarse no activa las herramientas de pago.", "En Connectors, use una cuenta PostgreSQL dedicada con permisos SELECT. Su administrador debe configurar red y TLS sin exponer la base a toda internet.", "Autorice la tabla de facturas, las columnas de importe y fecha y la moneda. Use únicamente datos autorizados.", "En Report tools, seleccione fuente y mes, compare periodos y exporte CSV. Las fechas usan UTC. El chat requiere un proveedor de IA configurado y acceso activo."],
    installTitle: "Web y acceso local opcional", web: "Web: abra dpsoft.space/workspace en un navegador actualizado; no necesita instalar una aplicación. Las herramientas dependen de la configuración y del acceso activo.", mac: "Vista previa macOS: CLI con Node.js 22+ y acceso al código, no un instalador firmado. Permite emparejar y verificar la conexión manualmente. Guardar un informe de texto aprobado es una acción local independiente, sin tareas desde la nube.", mobile: "Móvil: acceso desde el navegador. No hay aplicaciones nativas iOS/Android, modo sin conexión ni control de otras apps.",
    securityTitle: "Controles y límites", security: "HTTPS, credenciales de conectores cifradas, comprobaciones por organización, consultas de solo lectura y eventos de auditoría. Los códigos caducan en 10 minutos y los tokens de dispositivo en 30 días; son revocables. No se garantiza seguridad absoluta ni certificación. No se afirma una auditoría independiente. El CLI guarda credenciales en un archivo restringido, no en el Llavero de macOS.",
    faqTitle: "Preguntas frecuentes", faq: [
      ["¿Qué sistemas puedo conectar?", "Actualmente PostgreSQL. MCP no convierte cualquier software en compatible; otras integraciones requieren desarrollo y pruebas."],
      ["¿El resultado es beneficio?", "No: es la suma del campo autorizado durante el mes UTC. No equivale automáticamente a beneficio, cobros o ingresos ajustados a impuestos. Compruebe la moneda y las definiciones."],
      ["¿Modifica mis registros?", "La consulta actual es de solo lectura. No hay modificaciones remotas ni control autónomo de aplicaciones."],
      ["¿Envía facturas por email o WhatsApp?", "Todavía no. Exporte CSV/JSON para revisar y compartir manualmente. Tampoco se incluye emisión fiscal de facturas."],
      ["¿Qué datos recibe la IA?", "El chat envía la pregunta y el resultado autorizado al proveedor configurado. El informe directo no llama a la IA. Evite datos sensibles innecesarios."],
      ["¿Hay instalador para Mac?", "Solo un CLI técnico compilable con Node.js 22+. La aplicación notarizada, las actualizaciones automáticas y las tareas remotas siguen pendientes."],
      ["¿Puedo comprar ya?", "Los tres planes son propuestas. Las compras están cerradas hasta configurar pagos y aplicar límites. Las cuotas propuestas no son prestaciones activas; confirme precio y moneda en el checkout cuando esté disponible."],
      ["¿El emparejamiento controla mi ordenador?", "No, solo permite verificar la conexión. No concede acceso a pantalla, teclado o archivos. Puede revocarlo en Connectors."],
      ["¿Puedo cancelar y exportar?", "El portal Stripe, cuando se configure, permite gestionar la suscripción según sus condiciones. CSV/JSON exportan informes o evidencias cargadas, no toda la cuenta. No hay eliminación de cuenta por autoservicio."],
      ["¿Por qué cambia la moneda?", "La conversión local es indicativa. La moneda del checkout y las comisiones bancarias determinan la liquidación. Idioma y moneda pueden cambiarse manualmente."]
    ], docs: "Guía técnica de instalación", planNote: "Propuesta de lanzamiento: compras cerradas hasta aplicar los límites.", plannedRuns: "Ejecuciones estándar propuestas / mes", audiences: ["Análisis de facturación enfocado.", "Análisis recurrentes en crecimiento.", "Operaciones de mayor volumen con presupuesto definido."]
  },
  fr: {
    title: "Comprenez les données de votre entreprise.", intro: "DPsoft relie une source PostgreSQL autorisée à un espace d’analyse du chiffre d’affaires facturé, de comparaison mensuelle et de vérification des sources. Il complète vos logiciels sans remplacer la comptabilité ni contrôler tous les ordinateurs.",
    valueTitle: "Une utilité concrète", value: "Retrouvez un calcul autorisé sans le reconstruire à chaque consultation. Vérifiez sa source, son mois et le nombre d’enregistrements. Le gain dépend de vos données et de votre processus ; votre équipe reste responsable de la validation financière.",
    stepsTitle: "Comment commencer", steps: ["Créez un compte et une organisation. Le propriétaire gère facturation et appareils ; l’inscription seule n’active pas les outils payants.", "Dans Connectors, utilisez un compte PostgreSQL dédié avec droits SELECT. Votre administrateur configure réseau et TLS sans exposer la base à tout internet.", "Autorisez la table des factures, les colonnes de montant et de date et la devise. Utilisez uniquement des données autorisées.", "Dans Report tools, sélectionnez la source et le mois, comparez et exportez en CSV. Les dates sont en UTC. Le chat nécessite un fournisseur IA configuré et un accès actif."],
    installTitle: "Le navigateur d’abord", web: "Web : ouvrez dpsoft.space/workspace dans un navigateur récent, sans application à installer. Les outils dépendent de la configuration et des droits d’accès.", mac: "Aperçu technique macOS : outil en ligne de commande avec Node.js 22+ et accès au code, pas un installateur signé. Il associe un appareil et vérifie manuellement la connexion. L’enregistrement approuvé d’un rapport texte reste une action locale séparée, sans tâches distantes.", mobile: "Mobile : utilisez le navigateur. Applications natives iOS/Android, mode hors ligne et contrôle d’autres applications ne sont pas disponibles.",
    securityTitle: "Des contrôles, pas une promesse absolue", security: "HTTPS, identifiants de connecteurs chiffrés, contrôles par organisation, requêtes en lecture seule et événements d’audit. Codes valables 10 minutes et jetons d’appareil 30 jours, révocables. Aucune sécurité absolue, certification ou revue indépendante n’est revendiquée. Le CLI conserve les identifiants dans un fichier à permissions restreintes, pas dans le Trousseau macOS.",
    faqTitle: "Questions fréquentes", faq: [
      ["Quels logiciels sont compatibles ?", "PostgreSQL est actuellement implémenté. MCP ne rend pas tous les logiciels compatibles ; chaque autre intégration exige développement et tests."],
      ["Le montant représente-t-il le bénéfice ?", "Non : c’est la somme du champ autorisé sur le mois UTC, pas automatiquement le bénéfice, les encaissements ou un revenu corrigé des taxes. Vérifiez devise et définitions."],
      ["Mes données sont-elles modifiées ?", "La requête actuelle est en lecture seule. Les modifications distantes et le contrôle autonome d’applications ne sont pas actifs."],
      ["Peut-on envoyer des factures par email ou WhatsApp ?", "Pas encore. Exportez CSV/JSON pour révision et partage manuel. L’émission fiscale de factures n’est pas incluse."],
      ["Quelles données reçoit le fournisseur IA ?", "Le chat transmet la question et le résultat autorisé au fournisseur configuré. Le rapport direct ne nécessite pas d’appel IA. Évitez les données sensibles inutiles."],
      ["Existe-t-il un installateur Mac ?", "Seulement un CLI technique à compiler avec Node.js 22+. Application notariée, mises à jour automatiques et tâches distantes restent à développer."],
      ["Puis-je acheter un abonnement ?", "Les trois offres sont des propositions. Les achats restent fermés jusqu’à configuration des paiements et application des limites. Les quotas proposés ne sont pas des droits actifs ; vérifiez le prix et la devise au paiement lorsqu’il sera disponible."],
      ["L’association donne-t-elle accès à mon ordinateur ?", "Non : elle permet uniquement de vérifier la connexion, sans accès à l’écran, au clavier ou aux fichiers. Révoquez l’appareil dans Connectors."],
      ["Puis-je résilier et exporter ?", "Une fois configuré, le portail Stripe permet de gérer l’abonnement selon ses conditions. CSV/JSON exportent des rapports ou preuves chargées, pas un compte complet. La suppression de compte en libre-service n’est pas disponible."],
      ["Pourquoi la devise affichée varie-t-elle ?", "La conversion locale est indicative. La devise du paiement et les frais bancaires déterminent le montant réglé. Langue et devise sont modifiables manuellement."]
    ], docs: "Guide technique d’installation", planNote: "Proposition de lancement : achats fermés jusqu’à application des limites.", plannedRuns: "Exécutions standard proposées / mois", audiences: ["Un processus ciblé d’analyse de facturation.", "Un volume croissant d’analyses récurrentes.", "Des opérations à plus grand volume et budget défini."]
  },
  de: {
    title: "Verstehen Sie Ihre Geschäftsdaten.", intro: "DPsoft verbindet eine freigegebene PostgreSQL-Quelle mit einem Arbeitsbereich für monatliche Rechnungsumsätze, Periodenvergleiche und Quellenprüfung. Es ergänzt bestehende Software, ersetzt aber weder Buchhaltung noch einen universellen Computerbediener.",
    valueTitle: "Konkreter Nutzen", value: "Rufen Sie eine freigegebene Berechnung ab, ohne sie jedes Mal neu aufzubauen. Prüfen Sie Quelle, Monat und Datensatzanzahl. Eine Zeitersparnis hängt von Datenqualität und Arbeitsablauf ab; die finanzielle Prüfung bleibt bei Ihrem Team.",
    stepsTitle: "So beginnen Sie", steps: ["Erstellen Sie Konto und Organisation. Der Eigentümer verwaltet Abrechnung und Geräte. Eine Registrierung allein aktiviert keine kostenpflichtigen Werkzeuge.", "Nutzen Sie unter Connectors ein eigenes PostgreSQL-Konto mit SELECT-Rechten. Ihr Administrator richtet Netzwerk und TLS ein, ohne die Datenbank für das gesamte Internet zu öffnen.", "Geben Sie Rechnungstabelle, Betrags- und Datumsspalte sowie Quellwährung frei. Verwenden Sie nur berechtigte Daten.", "Wählen Sie unter Report tools Quelle und Monat, vergleichen Sie Zeiträume und exportieren Sie CSV. Datumsgrenzen verwenden UTC. Der Chat benötigt zusätzlich einen konfigurierten KI-Anbieter und aktiven Zugang."],
    installTitle: "Im Browser starten", web: "Web: Öffnen Sie dpsoft.space/workspace in einem aktuellen Browser. Keine Desktop-Installation erforderlich. Werkzeuge hängen von Konfiguration und Zugangsrechten ab.", mac: "Technische macOS-Vorschau: CLI mit Node.js 22+ und Quellcodezugang, kein signiertes Installationsprogramm. Es koppelt Geräte und prüft die Verbindung manuell. Freigegebene Textberichte werden separat lokal gespeichert; Cloud-Aufträge werden nicht ausgeführt.", mobile: "Mobil: Nutzung im Browser. Native iOS-/Android-Apps, Offline-Modus und die Steuerung anderer Apps sind nicht verfügbar.",
    securityTitle: "Kontrollen mit klaren Grenzen", security: "HTTPS, verschlüsselt gespeicherte Connector-Zugangsdaten, Organisationsprüfungen, reine Leseabfragen und Audit-Ereignisse. Kopplungscodes gelten 10 Minuten, widerrufbare Geräte-Token 30 Tage. Keine Garantie absoluter Sicherheit, Zertifizierung oder Behauptung eines unabhängigen Audits. Das CLI speichert Zugangsdaten in einer zugriffsbeschränkten Datei, nicht im macOS-Schlüsselbund.",
    faqTitle: "Häufige Fragen", faq: [
      ["Welche Software lässt sich verbinden?", "Derzeit ist PostgreSQL implementiert. MCP macht nicht jede Software kompatibel; weitere Integrationen benötigen Entwicklung und Tests."],
      ["Ist der Betrag mein Gewinn?", "Nein: Er summiert das freigegebene Feld im UTC-Monat und entspricht nicht automatisch Gewinn, Zahlungseingängen oder steuerbereinigten Erlösen. Währung und Definitionen müssen geprüft werden."],
      ["Werden Geschäftsdaten geändert?", "Das aktuelle Umsatzwerkzeug liest nur. Fernänderungen und autonome App-Steuerung sind nicht aktiviert."],
      ["Versendet es Rechnungen per E-Mail oder WhatsApp?", "Noch nicht. CSV/JSON können zur manuellen Prüfung und Weitergabe exportiert werden. Steuerrechtliche Rechnungserstellung ist nicht enthalten."],
      ["Welche Daten erhält der KI-Anbieter?", "Im Chat werden Frage und freigegebenes Werkzeugergebnis an den konfigurierten Anbieter gesendet. Direkte Berichte benötigen keinen KI-Aufruf. Vermeiden Sie unnötige sensible Daten."],
      ["Gibt es ein Mac-Installationsprogramm?", "Nur ein technisches CLI zum Erstellen mit Node.js 22+. Notarisierte App, automatische Updates und Fernaufträge stehen noch aus."],
      ["Kann ich ein Abo kaufen?", "Die drei Tarife sind Vorschläge. Käufe bleiben bis zur Zahlungs- und Limitkonfiguration geschlossen. Vorgeschlagene Kontingente sind keine aktiven Ansprüche; prüfen Sie später Betrag und Währung im Checkout."],
      ["Erlaubt die Kopplung Zugriff auf meinen Computer?", "Nein: Sie erlaubt nur die Verbindungsprüfung, keinen Bildschirm-, Tastatur- oder Dateizugriff. Geräte lassen sich unter Connectors widerrufen."],
      ["Kann ich kündigen und Daten exportieren?", "Das Stripe-Portal erlaubt nach Konfiguration die Aboverwaltung gemäß den angezeigten Bedingungen. CSV/JSON exportieren Berichte bzw. geladene Nachweise, kein vollständiges Kontoarchiv. Eine selbstständige Kontolöschung fehlt noch."],
      ["Warum weicht die angezeigte Währung ab?", "Lokale Umrechnungen sind unverbindlich. Checkout-Währung und Bankgebühren bestimmen die Zahlung. Sprache und Währung sind manuell wählbar."]
    ], docs: "Technische Installationsanleitung", planNote: "Startangebot in Planung: Käufe bleiben bis zur Durchsetzung der Limits geschlossen.", plannedRuns: "Geplante Standardausführungen / Monat", audiences: ["Für gezielte Rechnungsumsatzanalysen.", "Für wachsende, wiederkehrende Analysen.", "Für größere Abläufe mit festgelegtem Budget."]
  }
};
