CREATE TYPE "MembershipStatus" AS ENUM ('INVITED','ACTIVE','SUSPENDED');
CREATE TYPE "ConnectorStatus" AS ENUM ('DRAFT','CONNECTED','DEGRADED','OFFLINE','ERROR','AUTH_REQUIRED');
CREATE TYPE "ToolMode" AS ENUM ('READ','WRITE');
CREATE TYPE "RiskLevel" AS ENUM ('LOW','MEDIUM','HIGH','CRITICAL');
CREATE TYPE "ApprovalStatus" AS ENUM ('PENDING','APPROVED','REJECTED','EXPIRED','CANCELLED','EXECUTED','FAILED');
CREATE TYPE "AuditStatus" AS ENUM ('SUCCESS','FAILURE','DENIED','PENDING_APPROVAL');

CREATE TABLE "Organization" ("id" UUID PRIMARY KEY, "name" TEXT NOT NULL, "slug" TEXT NOT NULL UNIQUE, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3));
CREATE TABLE "User" ("id" UUID PRIMARY KEY, "email" TEXT NOT NULL UNIQUE, "passwordHash" TEXT NOT NULL, "displayName" TEXT NOT NULL, "emailVerified" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3));
CREATE TABLE "Membership" ("id" UUID PRIMARY KEY, "organizationId" UUID NOT NULL, "userId" UUID NOT NULL, "status" "MembershipStatus" NOT NULL DEFAULT 'INVITED', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE("organizationId","userId"));
CREATE TABLE "Role" ("id" UUID PRIMARY KEY, "organizationId" UUID NOT NULL, "name" TEXT NOT NULL, "isSystem" BOOLEAN NOT NULL DEFAULT false, UNIQUE("organizationId","name"));
CREATE TABLE "Permission" ("id" UUID PRIMARY KEY, "key" TEXT NOT NULL UNIQUE, "description" TEXT NOT NULL);
CREATE TABLE "RolePermission" ("roleId" UUID NOT NULL, "permissionId" UUID NOT NULL, PRIMARY KEY("roleId","permissionId"));
CREATE TABLE "MembershipRole" ("membershipId" UUID NOT NULL, "roleId" UUID NOT NULL, PRIMARY KEY("membershipId","roleId"));
CREATE TABLE "ConnectorDefinition" ("id" UUID PRIMARY KEY, "key" TEXT NOT NULL UNIQUE, "name" TEXT NOT NULL, "description" TEXT NOT NULL, "category" TEXT NOT NULL);
CREATE TABLE "ConnectorInstance" ("id" UUID PRIMARY KEY, "organizationId" UUID NOT NULL, "connectorDefinitionId" UUID NOT NULL, "name" TEXT NOT NULL, "status" "ConnectorStatus" NOT NULL DEFAULT 'DRAFT', "environment" TEXT NOT NULL, "encryptedCredential" BYTEA, "configuration" JSONB NOT NULL DEFAULT '{}', "allowedSchema" JSONB NOT NULL DEFAULT '{}', "lastHeartbeatAt" TIMESTAMP(3), "lastSuccessfulAt" TIMESTAMP(3), "lastErrorCode" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3));
CREATE TABLE "Session" ("id" UUID PRIMARY KEY, "organizationId" UUID, "userId" UUID NOT NULL, "tokenHash" TEXT NOT NULL UNIQUE, "expiresAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "revokedAt" TIMESTAMP(3));
CREATE TABLE "Tool" ("id" UUID PRIMARY KEY, "connectorInstanceId" UUID NOT NULL, "name" TEXT NOT NULL, "description" TEXT NOT NULL, "inputSchema" JSONB NOT NULL, "outputSchema" JSONB NOT NULL, "mode" "ToolMode" NOT NULL, "riskLevel" "RiskLevel" NOT NULL, "requiresApproval" BOOLEAN NOT NULL DEFAULT false, "enabled" BOOLEAN NOT NULL DEFAULT true, UNIQUE("connectorInstanceId","name"));
CREATE TABLE "ToolPermission" ("toolId" UUID NOT NULL, "permissionId" UUID NOT NULL, PRIMARY KEY("toolId","permissionId"));
CREATE TABLE "Agent" ("id" UUID PRIMARY KEY, "organizationId" UUID NOT NULL, "name" TEXT NOT NULL, "description" TEXT NOT NULL, "instructions" TEXT NOT NULL, "modelProvider" TEXT NOT NULL, "modelName" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "AgentConnector" ("agentId" UUID NOT NULL, "connectorId" UUID NOT NULL, PRIMARY KEY("agentId","connectorId"));
CREATE TABLE "AgentTool" ("agentId" UUID NOT NULL, "toolId" UUID NOT NULL, PRIMARY KEY("agentId","toolId"));
CREATE TABLE "Approval" ("id" UUID PRIMARY KEY, "organizationId" UUID NOT NULL, "toolId" UUID NOT NULL, "requestedById" UUID NOT NULL, "decidedById" UUID, "status" "ApprovalStatus" NOT NULL DEFAULT 'PENDING', "inputDigest" TEXT NOT NULL, "inputEncrypted" BYTEA NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "decidedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AuditLog" ("id" UUID PRIMARY KEY, "organizationId" UUID NOT NULL, "actorId" UUID, "requestId" TEXT NOT NULL, "action" TEXT NOT NULL, "resourceType" TEXT NOT NULL, "resourceId" TEXT, "connectorId" TEXT, "toolId" TEXT, "riskLevel" "RiskLevel", "status" "AuditStatus" NOT NULL, "metadata" JSONB NOT NULL, "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Conversation" ("id" UUID PRIMARY KEY, "organizationId" UUID NOT NULL, "userId" UUID NOT NULL, "agentId" UUID NOT NULL, "title" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Message" ("id" UUID PRIMARY KEY, "conversationId" UUID NOT NULL, "role" TEXT NOT NULL, "content" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE INDEX "Membership_userId_status_idx" ON "Membership"("userId","status");
CREATE INDEX "ConnectorInstance_organizationId_status_idx" ON "ConnectorInstance"("organizationId","status");
CREATE INDEX "Session_userId_expiresAt_idx" ON "Session"("userId","expiresAt");
CREATE INDEX "Session_organizationId_expiresAt_idx" ON "Session"("organizationId","expiresAt");
CREATE INDEX "Agent_organizationId_active_idx" ON "Agent"("organizationId","active");
CREATE INDEX "Approval_organizationId_status_createdAt_idx" ON "Approval"("organizationId","status","createdAt");
CREATE INDEX "AuditLog_organizationId_occurredAt_idx" ON "AuditLog"("organizationId","occurredAt" DESC);
CREATE INDEX "AuditLog_organizationId_action_occurredAt_idx" ON "AuditLog"("organizationId","action","occurredAt" DESC);
CREATE INDEX "AuditLog_requestId_idx" ON "AuditLog"("requestId");
CREATE INDEX "Conversation_organizationId_updatedAt_idx" ON "Conversation"("organizationId","updatedAt" DESC);
CREATE INDEX "Message_conversationId_createdAt_idx" ON "Message"("conversationId","createdAt");

ALTER TABLE "Membership" ADD CONSTRAINT "Membership_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Role" ADD CONSTRAINT "Role_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_permissionId_fkey" FOREIGN KEY ("permissionId") REFERENCES "Permission"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MembershipRole" ADD CONSTRAINT "MembershipRole_membershipId_fkey" FOREIGN KEY ("membershipId") REFERENCES "Membership"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MembershipRole" ADD CONSTRAINT "MembershipRole_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ConnectorInstance" ADD CONSTRAINT "ConnectorInstance_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ConnectorInstance" ADD CONSTRAINT "ConnectorInstance_connectorDefinitionId_fkey" FOREIGN KEY ("connectorDefinitionId") REFERENCES "ConnectorDefinition"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Tool" ADD CONSTRAINT "Tool_connectorInstanceId_fkey" FOREIGN KEY ("connectorInstanceId") REFERENCES "ConnectorInstance"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ToolPermission" ADD CONSTRAINT "ToolPermission_toolId_fkey" FOREIGN KEY ("toolId") REFERENCES "Tool"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ToolPermission" ADD CONSTRAINT "ToolPermission_permissionId_fkey" FOREIGN KEY ("permissionId") REFERENCES "Permission"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Agent" ADD CONSTRAINT "Agent_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AgentConnector" ADD CONSTRAINT "AgentConnector_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "Agent"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AgentConnector" ADD CONSTRAINT "AgentConnector_connectorId_fkey" FOREIGN KEY ("connectorId") REFERENCES "ConnectorInstance"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AgentTool" ADD CONSTRAINT "AgentTool_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "Agent"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AgentTool" ADD CONSTRAINT "AgentTool_toolId_fkey" FOREIGN KEY ("toolId") REFERENCES "Tool"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Approval" ADD CONSTRAINT "Approval_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Approval" ADD CONSTRAINT "Approval_decidedById_fkey" FOREIGN KEY ("decidedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "Agent"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Message" ADD CONSTRAINT "Message_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
